const setValue = (location: string, index: number, indexs: any) => {
  let cell = TravelPath.playars.map((path: any, index: number) => {
    if (path.location === location && path.index === index)
      return { ...path, layout: indexs };
  });
};

const coins = [
  {
    layout: {},
    index: 0,
  },
  {
    layout: {},
    index: 1,
  },
  {
    layout: {},
    index: 2,
  },
  {
    layout: {},
    index: 3,
  },
  {
    layout: {},
    index: 4,
  },
];

export const PlayersHome = {
  topLeftHome: [],
  topRightHome: [],
  bottomLeftHome: [],
  bottomRightHome: [],
};

export const getPlayer1Paths = () => {
  return [
    { location: "bottomLeft", index: 0 },
    { location: "bottomLeft", index: 1 },
    { location: "bottomLeft", index: 2 },
    { location: "bottomLeft", index: 3 },
    { location: "bottom", index: 20 },
    { location: "bottom", index: 21 },
    { location: "bottom", index: 16 },
    { location: "bottom", index: 11 },
    { location: "bottom", index: 6 },
    { location: "bottom", index: 1 },
    { location: "bottom", index: 0 },
    { location: "left", index: 14 },
    { location: "left", index: 13 },
    { location: "left", index: 12 },
    { location: "left", index: 11 },
    { location: "left", index: 10 },
    { location: "left", index: 5 },
    { location: "left", index: 0 },
    { location: "left", index: 1 },
    { location: "left", index: 2 },
    { location: "left", index: 3 },
    { location: "left", index: 4 },
    { location: "top", index: 20 },
    { location: "top", index: 21 },
    { location: "top", index: 16 },
    { location: "top", index: 11 },
    { location: "top", index: 6 },
    { location: "top", index: 1 },
    { location: "top", index: 2 },
    { location: "top", index: 3 },
    { location: "top", index: 8 },
    { location: "top", index: 13 },
    { location: "top", index: 18 },
    { location: "top", index: 23 },
    { location: "top", index: 24 },
    { location: "right", index: 0 },
    { location: "right", index: 1 },
    { location: "right", index: 2 },
    { location: "right", index: 3 },
    { location: "right", index: 4 },
    { location: "right", index: 9 },
    { location: "right", index: 14 },
    { location: "right", index: 13 },
    { location: "right", index: 12 },
    { location: "right", index: 11 },
    { location: "right", index: 10 },
    { location: "bottom", index: 4 },
    { location: "bottom", index: 3 },
    { location: "bottom", index: 8 },
    { location: "bottom", index: 13 },
    { location: "bottom", index: 18 },
    { location: "bottom", index: 23 },
    { location: "bottom", index: 22 },
    { location: "bottom", index: 17 },
    { location: "bottom", index: 12 },
    { location: "bottom", index: 7 },
    { location: "bottom", index: 2 },
    { location: "playerHome1", index: 0 },
  ];
};

export const getPlayer2Paths = () => {
  return [
    { location: "topLeft", index: 0 },
    { location: "topLeft", index: 1 },
    { location: "topLeft", index: 2 },
    { location: "topLeft", index: 3 },
    { location: "topLeft", index: 4 },
    { location: "left", index: 0 },
    { location: "left", index: 1 },
    { location: "left", index: 2 },
    { location: "left", index: 3 },
    { location: "left", index: 4 },
    { location: "top", index: 20 },
    { location: "top", index: 21 },
    { location: "top", index: 16 },
    { location: "top", index: 11 },
    { location: "top", index: 6 },
    { location: "top", index: 1 },
    { location: "top", index: 2 },
    { location: "top", index: 3 },
    { location: "top", index: 8 },
    { location: "top", index: 13 },
    { location: "top", index: 18 },
    { location: "top", index: 23 },
    { location: "top", index: 24 },
    { location: "right", index: 0 },
    { location: "right", index: 1 },
    { location: "right", index: 2 },
    { location: "right", index: 3 },
    { location: "right", index: 4 },
    { location: "right", index: 9 },
    { location: "right", index: 14 },
    { location: "right", index: 13 },
    { location: "right", index: 12 },
    { location: "right", index: 11 },
    { location: "right", index: 10 },
    { location: "bottom", index: 4 },
    { location: "bottom", index: 3 },
    { location: "bottom", index: 8 },
    { location: "bottom", index: 13 },
    { location: "bottom", index: 18 },
    { location: "bottom", index: 23 },
    { location: "bottom", index: 22 },
    { location: "bottom", index: 21 },
    { location: "bottom", index: 16 },
    { location: "bottom", index: 11 },
    { location: "bottom", index: 6 },
    { location: "bottom", index: 1 },
    { location: "bottom", index: 0 },
    { location: "left", index: 14 },
    { location: "left", index: 13 },
    { location: "left", index: 12 },
    { location: "left", index: 11 },
    { location: "left", index: 10 },
    { location: "left", index: 5 },
    { location: "left", index: 6 },
    { location: "left", index: 7 },
    { location: "left", index: 8 },
    { location: "left", index: 9 },
    { location: "playerHome2", index: 0 },
  ];
};

export const getPlayer3Paths = () => {
  return [
    { location: "topRight", index: 3 },
    { location: "topRight", index: 2 },
    { location: "topRight", index: 1 },
    { location: "topRight", index: 0 },
    { location: "top", index: 4 },
    { location: "top", index: 3 },
    { location: "top", index: 8 },
    { location: "top", index: 13 },
    { location: "top", index: 18 },
    { location: "top", index: 23 },
    { location: "top", index: 24 },
    { location: "right", index: 0 },
    { location: "right", index: 1 },
    { location: "right", index: 2 },
    { location: "right", index: 3 },
    { location: "right", index: 4 },
    { location: "right", index: 9 },
    { location: "right", index: 14 },
    { location: "right", index: 13 },
    { location: "right", index: 12 },
    { location: "right", index: 11 },
    { location: "right", index: 10 },
    { location: "bottom", index: 4 },
    { location: "bottom", index: 3 },
    { location: "bottom", index: 8 },
    { location: "bottom", index: 13 },
    { location: "bottom", index: 18 },
    { location: "bottom", index: 23 },
    { location: "bottom", index: 22 },
    { location: "bottom", index: 21 },
    { location: "bottom", index: 16 },
    { location: "bottom", index: 11 },
    { location: "bottom", index: 6 },
    { location: "bottom", index: 1 },
    { location: "bottom", index: 0 },
    { location: "left", index: 14 },
    { location: "left", index: 13 },
    { location: "left", index: 12 },
    { location: "left", index: 11 },
    { location: "left", index: 10 },
    { location: "left", index: 5 },
    { location: "left", index: 0 },
    { location: "left", index: 1 },
    { location: "left", index: 2 },
    { location: "left", index: 3 },
    { location: "left", index: 4 },
    { location: "top", index: 20 },
    { location: "top", index: 21 },
    { location: "top", index: 16 },
    { location: "top", index: 11 },
    { location: "top", index: 6 },
    { location: "top", index: 1 },
    { location: "top", index: 2 },
    { location: "top", index: 7 },
    { location: "top", index: 12 },
    { location: "top", index: 17 },
    { location: "top", index: 22 },
    { location: "playerHome3", index: 0 },
  ];
};

export const getPlayer4Paths = () => {
  return [
    { location: "bottomRight", index: 4 },
    { location: "bottomRight", index: 3 },
    { location: "bottomRight", index: 2 },
    { location: "bottomRight", index: 1 },
    { location: "bottomRight", index: 0 },
    { location: "right", index: 14 },
    { location: "right", index: 13 },
    { location: "right", index: 12 },
    { location: "right", index: 11 },
    { location: "right", index: 10 },
    { location: "bottom", index: 4 },
    { location: "bottom", index: 3 },
    { location: "bottom", index: 8 },
    { location: "bottom", index: 13 },
    { location: "bottom", index: 18 },
    { location: "bottom", index: 23 },
    { location: "bottom", index: 22 },
    { location: "bottom", index: 21 },
    { location: "bottom", index: 16 },
    { location: "bottom", index: 11 },
    { location: "bottom", index: 6 },
    { location: "bottom", index: 1 },
    { location: "bottom", index: 0 },
    { location: "left", index: 14 },
    { location: "left", index: 13 },
    { location: "left", index: 12 },
    { location: "left", index: 11 },
    { location: "left", index: 10 },
    { location: "left", index: 5 },
    { location: "left", index: 0 },
    { location: "left", index: 1 },
    { location: "left", index: 2 },
    { location: "left", index: 3 },
    { location: "left", index: 4 },
    { location: "top", index: 20 },
    { location: "top", index: 21 },
    { location: "top", index: 16 },
    { location: "top", index: 11 },
    { location: "top", index: 6 },
    { location: "top", index: 1 },
    { location: "top", index: 2 },
    { location: "top", index: 3 },
    { location: "top", index: 8 },
    { location: "top", index: 13 },
    { location: "top", index: 18 },
    { location: "top", index: 23 },
    { location: "top", index: 24 },
    { location: "right", index: 0 },
    { location: "right", index: 1 },
    { location: "right", index: 2 },
    { location: "right", index: 3 },
    { location: "right", index: 4 },
    { location: "right", index: 9 },
    { location: "right", index: 8 },
    { location: "right", index: 7 },
    { location: "right", index: 6 },
    { location: "right", index: 5 },
    { location: "playerHome4", index: 0 },
  ];
};

export const TravelPath = {
  playars: [
    { path: getPlayer1Paths(), home: PlayersHome.bottomLeftHome },
    /*  { path: getPlayer1Paths(), home: PlayersHome.topLeftHome },
    { path: getPlayer1Paths(), home: PlayersHome.topRightHome },
    { path: getPlayer1Paths(), home: PlayersHome.bottomRightHome }, */
  ],
};

export const HOMES = ["topLeft", "topRight", "bottomLeft", "bottomRight"];

export const SAFEZONE = [
  { location: "top", index: 3 },
  { location: "top", index: 21 },
  { location: "top", index: 25 },
  { location: "bottom", index: 1 },
  { location: "bottom", index: 5 },
  { location: "bottom", index: 23 },
  { location: "left", index: 6 },
  { location: "right", index: 10 },
];
