export const TravelPath = {
  playars: [
    [
      { location: "home", position: 0 },
      { location: "bottom", position: 2 },
      { location: "bottom", position: 7 },
      { location: "bottom", position: 12 },
      { location: "bottom", position: 17 },
      { location: "bottom", position: 22 },
      { location: "bottom", position: 21 },
      { location: "bottom", position: 16 },
      { location: "bottom", position: 11 },
      { location: "bottom", position: 6 },
      { location: "bottom", position: 1 },
      { location: "bottom", position: 0 },
      { location: "left", position: 14 },
      { location: "left", position: 13 },
      { location: "left", position: 12 },
      { location: "left", position: 11 },
      { location: "left", position: 10 },
      { location: "left", position: 5 },
      { location: "left", position: 0 },
      { location: "left", position: 1 },
      { location: "left", position: 2 },
      { location: "left", position: 3 },
      { location: "left", position: 4 },
      { location: "top", position: 20 },
      { location: "top", position: 21 },
      { location: "top", position: 16 },
      { location: "top", position: 11 },
      { location: "top", position: 6 },
      { location: "top", position: 1 },
      { location: "top", position: 2 },
      { location: "top", position: 3 },
      { location: "top", position: 8 },
      { location: "top", position: 13 },
      { location: "top", position: 18 },
      { location: "top", position: 23 },
      { location: "top", position: 24 },
      { location: "right", position: 0 },
      { location: "right", position: 1 },
      { location: "right", position: 2 },
      { location: "right", position: 3 },
      { location: "right", position: 4 },
      { location: "right", position: 9 },
      { location: "right", position: 14 },
      { location: "right", position: 13 },
      { location: "right", position: 12 },
      { location: "right", position: 11 },
      { location: "right", position: 10 },
      { location: "bottom", position: 4 },
      { location: "bottom", position: 3 },
      { location: "bottom", position: 8 },
      { location: "bottom", position: 13 },
      { location: "bottom", position: 18 },
      { location: "bottom", position: 23 },
      { location: "bottom", position: 22 },
      { location: "bottom", position: 17 },
      { location: "bottom", position: 12 },
      { location: "bottom", position: 7 },
      { location: "bottom", position: 2 },
      { location: "home", position: 0 },
    ],
  ],
};
